services:
  db:
    image: mysql:8.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_pass
    volumes: ['./docker/mysql/my.cnf:/etc/my.cnf']
  adminer:
    image: adminer:4.8.0-standalone
    ports: ['8091:8080']
  php:
    build: ./docker/php
    ports: ['8090:80']
    volumes: ['./app/:/var/www/html']